# Generated by Django 3.2.5 on 2021-08-06 07:10

import demo.cipher_field.cipher_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=demo.cipher_field.cipher_field.CipherCharField(blank=True, max_length=255, token=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=demo.cipher_field.cipher_field.CipherCharField(blank=True, max_length=255, token=None),
        ),
    ]
