# Generated by Django 3.2.5 on 2021-08-05 16:15

from django.db import migrations

from demo.cipher_migrate import encrypt_cipher_name, encrypt_cipher_phone, decrypt_cipher_name, decrypt_cipher_phone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(encrypt_cipher_name, decrypt_cipher_name),
        migrations.RunPython(encrypt_cipher_phone, decrypt_cipher_phone),
    ]
